[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
test = 'contracts/tests'
cache_path = 'forge-cache'
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config